preprocessing:
  change_ids_columns: ['purchase', 'supplier', 'customer']
  fillna_columns:
    item_descriptions: purchase_name
    purchase_name: okpd2_names
  sort_columns: ['supplier', 'min_publish_date']
  change_columns:
    forsmallbiz:
      t: 1
      f: 0
  change_type_columns:
    supplier: category
    reg_code: category
  drop_columns: ['region_code', 'okpd2_code', 'min_publish_date']
  text_columns: ['purchase_name', 'item_descriptions', 'okpd2_names']
  n-components: 100
  filter_column: supplier
  train_test_split:
    test_size: 0.2
    random_state: 42
    stratify: supplier
  recommend_submission:
    groupby: supplier
    values: purchase
    name: purchases
  winner_submission:
    column: is_winner
    name: is_winner
  month: min_publish_date
  region: region
  okpd2: okpd2_code
  purchase:
    groupby: purchase
    values: supplier
    name: purchase_size
    on: purchase
    how: outer
  flag:
    train_columns: ['supplier', 'customer', 'flag_won']
    groupby: ['suppleir', 'customer']
    on: ['supplier', 'customer']
    how: left
  uniq_okpd2:
    groupby: suppleir
    values: okpd2_code
    on: supplier
    name: n_unique_okpd2
  supplier_small_path: ../data/raw/small_suppliers.csv
  purchases_small_path: ../data/raw/small_purchases.csv
  supplier_path: ../data/raw/all_suppliers.csv
  purchase_path: ../data/raw/all_purchases.csv
  train_data: ../data/processed/train_data.csv
  test_data: ../data/processed/test_data.csv
  submission: ../data/check/submission.csv
  evaluate_data: ../data/check/evaluate_data.csv
  winning_evaluate: ../data/check/winning_evaluate.csv

train:
  drop_columns_recommender: ['supplier', 'reg_code', 'is_winner',
                             'vectorized_tokens', 'customer', 'flag_won',
                             'purchase_size', 'n_unique_okpd2']
  drop_columns_winner: ['vectorized_tokens', 'purchase', 'customer']
  recommender_params: ../models/params/recommender_params.yaml
  ensemble_params: ../models/params/ensemble_params.yaml
  recommender_models: ../models/models/recommender_models.joblib
  ensemble_models: ../models/models/ensemble_models.joblib
  cat_features: ['supplier', 'reg_code']
  random_state: 42
  N_FOLDS: 4
  test_size: 0.25

evaluate:
  submission: ../data/check/submission.csv
  evaluate_data: ../data/check/evaluate_data.csv
  winning_evaluate: ../data/check/winning_evaluate.csv



    
