preprocessing:
  change_columns:
    forsmallbiz:
      t: 1
      f: 0
  change_type_columns:
    min_publish_date: datetime64[D]
    supplier: category
    reg_code: category
  drop_columns: ['region_code', 'okpd2_code', 'min_publish_date']
  drop_text_columns: ['purchase_name', 'item_descriptions', 'okpd2_names']
  supplier_path: ../data/raw/small_suppliers.csv
  purchases_path: ../data/raw/small_purchases.csv
  train_data: ../data/processed/train_data.csv
  test_data: ../data/processed/test_data.csv
  submission: ../data/check/submission.csv
  submission_less_4: ../data/check/submission_less_4.csv
  test_evaluate: ../data/check/test_evaluate.csv
  winning_evaluate: ../data/check/winning_evaluate.csv

train:
  drop_columns_lgbm: ['supplier', 'min_publish_date', 'reg_code', 'is_winner', 'vectorized_tokens']
  drop_columns_catboost: ['vectorized_tokens', 'purchase', 'min_publish_date']
  lightgbm_params: model_params/lightgbm.yaml
  catboost_params: model_params/catboost.yaml
  random_state: 42
  N_FOLDS: 4
  test_size: 0.2

evaluate:
  submission: ../data/check/submission.csv
  submission_less_4: ../data/check/submission_less_4.csv




    
